In [1]:
import sys
import numpy as np
import pandas as pd

In [2]:
## Loading the data
deltashaperepone = pd.read_csv('../../deltaSHAPE_confirmed_sites/deltaSHAPE_rep1.igv',sep="\t")
deltashapereptwo = pd.read_csv('../../deltaSHAPE_confirmed_sites/deltaSHAPE_rep2.igv',sep="\t")
alldata  = pd.read_csv('../../big_dataframe_Xist_diffBUM_HMM_scaled_dc.txt',sep="\t",header=0,index_col=0)
previous = pd.read_csv('../../big_dataframe_Xist.txt',sep="\t",header=0,index_col=0)

In [3]:
alldata.head()

,nucleotide_number,nucleotide_identity,DeltaSHAPE_ex_vivo,DeltaSHAPE_in_cell,average_deltaSHAPE,CELF1,FUS,HuR,PTBP1,RBFOX2,TARDBP,diffBUMHMM_in_cell,diffBUMHMM_ex_vivo,dStruct_DDR
0,1,C,0,0,0.0,0,0,0,0,0,0,1.693237e-14,1.790644e-20,0
1,2,G,0,0,0.0,0,0,0,0,0,0,6.789051e-03,6.823904e-03,0
2,3,G,0,0,0.0,0,0,0,0,0,0,9.031615e-03,9.110841e-03,0
3,4,C,0,0,0.0,0,0,0,0,0,0,6.793530e-03,6.927069e-03,0
4,5,T,0,0,0.0,0,0,0,0,0,0,1.128597e-08,5.186918e-06,0

In [4]:
alldata[alldata.average_deltaSHAPE > 0].head()

,nucleotide_number,nucleotide_identity,DeltaSHAPE_ex_vivo,DeltaSHAPE_in_cell,average_deltaSHAPE,CELF1,FUS,HuR,PTBP1,RBFOX2,TARDBP,diffBUMHMM_in_cell,diffBUMHMM_ex_vivo,dStruct_DDR
209,210,T,1,0,1.365817,0,0,0,0,0,0,3.341549e-04,4.392628e-01,1
210,211,T,1,0,1.504202,0,0,0,0,0,0,6.123091e-24,1.242867e-52,1
211,212,T,1,0,1.721811,0,0,0,0,0,0,1.802013e-04,2.930757e-01,1
243,244,A,1,0,1.628085,0,0,1,0,0,0,2.619692e-12,3.105350e-56,1
244,245,T,1,0,2.116178,0,0,1,0,0,0,1.021677e-03,2.388718e-01,1

In [5]:
alldata.columns

Index(['nucleotide_number', 'nucleotide_identity', 'DeltaSHAPE_ex_vivo',
       'DeltaSHAPE_in_cell', 'average_deltaSHAPE', 'CELF1', 'FUS', 'HuR',
       'PTBP1', 'RBFOX2', 'TARDBP', 'diffBUMHMM_in_cell', 'diffBUMHMM_ex_vivo',
       'dStruct_DDR'],
      dtype='object')

In [6]:
alldata.columns[2:5]

Index(['DeltaSHAPE_ex_vivo', 'DeltaSHAPE_in_cell', 'average_deltaSHAPE'], dtype='object')

### Merging the two datasets and only keeping those that had deltaSHAPE values in both

In [7]:
merged = deltashaperepone.merge(deltashapereptwo)

In [8]:
merged.head()

  Chromosome  Start   End     Feature  deltaSHAPE  deltaSHAPE_rep1
0  mm10_XIST    247   248  deltaSHAPE    1.307304         1.398904
1  mm10_XIST    315   316  deltaSHAPE    1.747989         1.986579
2  mm10_XIST    316   317  deltaSHAPE    1.685508         1.707376
3  mm10_XIST    317   318  deltaSHAPE    1.280143         1.423275
4  mm10_XIST   4700  4701  deltaSHAPE   -1.373647         2.334900

In [9]:
col = merged[["deltaSHAPE","deltaSHAPE_rep1"]]
merged['average'] = col.mean(axis=1)

In [10]:
merged.head()

  Chromosome  Start   End     Feature  deltaSHAPE  deltaSHAPE_rep1   average
0  mm10_XIST    247   248  deltaSHAPE    1.307304         1.398904  1.353104
1  mm10_XIST    315   316  deltaSHAPE    1.747989         1.986579  1.867284
2  mm10_XIST    316   317  deltaSHAPE    1.685508         1.707376  1.696442
3  mm10_XIST    317   318  deltaSHAPE    1.280143         1.423275  1.351709
4  mm10_XIST   4700  4701  deltaSHAPE   -1.373647         2.334900  0.480626

In [11]:
merged.to_csv("../../deltaSHAPE_confirmed_sites/deltaSHAPE_merged_averaged.txt",sep="\t")

### Adding the new information to the big table:

In [12]:
alldata[alldata.columns[2:5]] = 0
previous[previous.columns[2:5]] = 0

In [13]:
subset = alldata[alldata.nucleotide_number.isin(merged.Start.values)].index

In [14]:
alldata.loc[subset,"average_deltaSHAPE"] = merged.average.values

In [15]:
alldata.loc[subset].head()

,nucleotide_number,nucleotide_identity,DeltaSHAPE_ex_vivo,DeltaSHAPE_in_cell,average_deltaSHAPE,CELF1,FUS,HuR,PTBP1,RBFOX2,TARDBP,diffBUMHMM_in_cell,diffBUMHMM_ex_vivo,dStruct_DDR
246,247,T,0,0,1.353104,0,0,1,0,0,0,1.960394e-02,6.764527e-01,1
314,315,T,0,0,1.867284,0,0,1,0,0,0,1.769283e-12,3.016913e-10,0
315,316,T,0,0,1.696442,0,0,1,0,0,0,2.198126e-26,2.210483e-31,0
316,317,C,0,0,1.351709,0,0,1,0,0,0,7.002605e-36,4.078121e-55,0
4699,4700,G,0,0,0.480626,0,1,0,0,0,0,1.242968e-16,1.643330e-77,0

In [16]:
alldata.head()

,nucleotide_number,nucleotide_identity,DeltaSHAPE_ex_vivo,DeltaSHAPE_in_cell,average_deltaSHAPE,CELF1,FUS,HuR,PTBP1,RBFOX2,TARDBP,diffBUMHMM_in_cell,diffBUMHMM_ex_vivo,dStruct_DDR
0,1,C,0,0,0.0,0,0,0,0,0,0,1.693237e-14,1.790644e-20,0
1,2,G,0,0,0.0,0,0,0,0,0,0,6.789051e-03,6.823904e-03,0
2,3,G,0,0,0.0,0,0,0,0,0,0,9.031615e-03,9.110841e-03,0
3,4,C,0,0,0.0,0,0,0,0,0,0,6.793530e-03,6.927069e-03,0
4,5,T,0,0,0.0,0,0,0,0,0,0,1.128597e-08,5.186918e-06,0

In [17]:
exvivoindex = alldata[alldata.average_deltaSHAPE > 1].index
invivoindex = alldata[alldata.average_deltaSHAPE < 1].index

In [18]:
alldata.loc[exvivoindex,"DeltaSHAPE_ex_vivo"] = 1
alldata.loc[invivoindex,"DeltaSHAPE_in_vivo"] = 1

In [19]:
previous.loc[exvivoindex,"DeltaSHAPE_ex_vivo"] = 1
previous.loc[invivoindex,"DeltaSHAPE_in_vivo"] = 1

In [21]:
alldata.to_csv('../../big_dataframe_Xist_diffBUM_HMM_scaled_dc_deltaSHAPE_corrected.txt',sep="\t")
previous.to_csv('../../big_dataframe_Xist_deltaSHAPE_corrected.txt',sep="\t")