In [4]:
import subprocess
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

Bad key "text.kerning_factor" on line 4 in
/anaconda3/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

In [11]:
%%bash

ls -l ../../

total 17864
drwxr-xr-x   6 sander  staff      192 10 Jun 15:05 Analysis
drwxr-xr-x  20 sander  staff      640 13 Jun 09:30 Control_rRNA_results
drwxr-xr-x  30 sander  staff      960 13 Jun 09:20 Data
drwxr-xr-x  16 sander  staff      512 21 May 09:30 Functions
drwxr-xr-x   3 sander  staff       96 21 May 09:28 Installation instructions March 2020 Update
drwxr-xr-x   9 sander  staff      288 13 Jun 12:50 Jupyter notebooks
-rw-r--r--@  1 sander  staff  3730760 10 Jun 13:18 New_data_table.txt
-rw-r--r--@  1 sander  staff  2510814 25 May 23:11 New_data_table.xlsx
drwxr-xr-x  26 sander  staff      832 10 Jun 14:51 Old
-rw-r--r--   1 sander  staff      592 21 May 09:28 README.md
drwxr-xr-x   9 sander  staff      288 10 Jun 13:20 Reference_sequences
drwxr-xr-x   9 sander  staff      288 13 Jun 09:31 Scripts
drwxr-xr-x  13 sander  staff      416 10 Jun 15:32 Secondary structure diagrams
-rw-r--r--   1 sander  staff  1387862 12 Jun 16:13 Xist in vivo vs. ex vivo_no_scaling_toby_diff_BUM_HMM_analysis.txt
-rw-r--r--   1 sander  staff   528741 12 Jun 16:13 Xist_ex_vivo_p-values.txt
-rw-r--r--   1 sander  staff   494603 12 Jun 16:13 Xist_in_cell_p-values.txt
-rw-r--r--   1 sander  staff    14438 12 Jun 16:13 Xist_sum_of_diff_states_diff_BUM_HMM_scaled_without_dc.png
drwxr-xr-x   2 sander  staff       64 12 Jun 16:14 diff_BUM_HMM

In [7]:
original_df = pd.read_csv('../../New_data_table.txt',
                          sep = '\t',
                          header = 0,
                          index_col = 0)

In [8]:
original_df.columns

Index(['nucleotide', 'CELF1', 'FUS', 'HuR', 'PTBP1', 'RBFOX2', 'TARDBP',
       'SHAPE_reactivity_ex_vivo_1', 'SHAPE_reactivity_ex_vivo_2',
       'SHAPE_reactivity_in_cell_1', 'SHAPE_reactivity_in_cell_2',
       'deltaSHAPE_rep1', 'deltaSHAPE_rep2', 'dStruct', 'dStruct_scaled',
       'unmodified', 'ex_vivo', 'in_vivo', 'both', 'scaled_unmodified',
       'scaled_ex_vivo', 'scaled_in_vivo', 'scaled_both'],
      dtype='object')

In [9]:
original_df['filteredUM'] = [0 if x < 0.95 else x for x in original_df['ex_vivo']]
original_df['filteredMU'] = [0 if x < 0.95 else x for x in original_df['in_vivo']]

In [10]:
original_df.head()

,nucleotide,CELF1,FUS,HuR,PTBP1,RBFOX2,TARDBP,SHAPE_reactivity_ex_vivo_1,SHAPE_reactivity_ex_vivo_2,SHAPE_reactivity_in_cell_1,...,unmodified,ex_vivo,in_vivo,both,scaled_unmodified,scaled_ex_vivo,scaled_in_vivo,scaled_both,filteredUM,filteredMU
1,C,0,0,0,0,0,0,-999.0,-999.0,-999.0,...,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.0,0.0
2,G,0,0,0,0,0,0,-999.0,-999.0,-999.0,...,0.712398,0.131639,0.131639,0.024325,0.712398,0.131639,0.131639,0.024325,0.0,0.0
3,G,0,0,0,0,0,0,-999.0,-999.0,-999.0,...,0.761379,0.111191,0.111191,0.016238,0.761379,0.111191,0.111191,0.016238,0.0,0.0
4,C,0,0,0,0,0,0,-999.0,-999.0,-999.0,...,0.795446,0.096432,0.096432,0.011690,0.795446,0.096432,0.096432,0.011690,0.0,0.0
5,T,0,0,0,0,0,0,-999.0,-999.0,-999.0,...,0.819621,0.085708,0.085708,0.008963,0.819621,0.085708,0.085708,0.008963,0.0,0.0

In [ ]:

df = original_df[['filteredUM','filteredMU']]

top_n = 1
A = pd.DataFrame({n: df.T[col].nlargest(top_n).index.tolist() for n, col in enumerate(df.T)}).T


list_of_ratios = []
iterations_counter =0

for iter in range(150):
    print('Iteration: ' +str(iter))
    subprocess.call("Rscript --vanilla ../../Scripts/diffBUM_HMM_0.8.R", shell=True)
        
    temp_df = pd.read_csv('C:/Users/maran/Desktop/diff_BUM_HMM_Project/Github/diff_BUM_HMM/Xist_in vivo_vs_ex vivo_diff_BUM_HMM_analysed_gaussian_noise_latest_xist_data.txt', sep="\t", header=0)
    
    
    
    
    if iter>0:
        print('This iter is larger than 0')
        check = temp_df.equals(ending_df)
        if check is True:
            print('Skipped this iteration')
            continue
        temporary_df=temp_df.copy()
        temporary_df= temporary_df.rename_axis('nt').reset_index()
        temporary_df['filteredUM'] = [0 if x<0.90 else x for x in temporary_df['UM']]
        temporary_df['filteredMU'] = [0 if x<0.90 else x for x in temporary_df['MU']]

        new_df= temporary_df[['filteredUM','filteredMU']]

        B = pd.DataFrame({n: new_df.T[col].nlargest(top_n).index.tolist() for n, col in enumerate(new_df.T)}).T

        counter=0
        other_counter=0
        for i in range(len(A.index)):
            if A.iloc[i:i+1,0:1].values[0][0] == B.iloc[i:i+1,0:1].values[0][0]:
                counter=counter+1
            else:
                other_counter=other_counter+1
 
    
        print(counter)
        print(other_counter)

        ratio = other_counter/counter
        print(ratio)
        list_of_ratios.append(ratio)
        del ratio
        del counter
        del other_counter
        del check
        del new_df

    ending_df=temp_df.copy()
    del temp_df
   
        #del B
        #del temporary_df
    
    
    iterations_counter=iterations_counter+1 
    










list_of_ratios_np = np.array(list_of_ratios).astype(np.float)
print('Mean is ' + str(np.mean(list_of_ratios_np)))
print('SD is ' + str(np.std(list_of_ratios_np)))
print('# of actual iterations' +str(iterations_counter))


#sys.stdout = open('file.txt', 'w')